# rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quotaguard-role
rules:
  - apiGroups: ["quota.malyue.com"]
    resources: ["quotapolicies"]
    verbs: ["get", "list", "watch"]  # 根据需求调整权限
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quotaguard-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: webhook-system
roleRef:
  kind: ClusterRole
  name: quotaguard-role
  apiGroup: rbac.authorization.k8s.io