apiVersion: v1
kind: Pod
metadata:
  name: test-pod-allowed
  namespace: quota  # 必须匹配 QuotaPolicy 中的 target.key
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1.5"
          memory: "2Gi"